# configuration settings not settable in gui
#
# Can make use of an !include tag with a file path to load additional config settings
# from other yaml files. If using the tag, load this file with PyYAML as follows:
#
# import yaml
# 
# def yaml_include(loader, node):
#     with file(node.value) as f:
#         return yaml.load(f)
#
# yaml.add_constructor("!include", yaml_include)  
# 
# with open("example_config.yaml", "r") as f:
#     config = yaml.load(f, Loader=yaml.FullLoader)  

# configuration of configuration
# relative paths given here are taken to be relative to the user's home directory
meta:
    # any .yaml files found in this folder will be loaded as if they were inline in this file
    # for duplicated config parameters, those in this directory will take precidence
    include_path: measurement_config.d

    # controls automatic gui configuration saving every time the run button is pressed
    autosave_enabled: true
    
    # folder used to store the gui configuration autosave files
    autosave_path: runconfigs

# user interface stuff
UI:
    # number of degrees to rotate the layout array drawing in the GUI
    # used so that the GUI display shows the same orientation as the user views the hardware from
    # with this zero, X (the 0th axis) is displayed horizonally and Y (the 1st axis) is vertically
    # best to leave this zero if making config adjustments, then set the rotation angle last
    # or else the other settings might get get confusing to set properly
    gui_drawing_rotation_angle: 90

    # default start-up values for the plot inversion switches
    invert_voltage: false
    invert_current: false

    # should we draw the user name box?
    show_user_box: true

    # should we show the custom webview tab?
    show_custom_tab: false

# maximum power point tracking configuration
mppt:
    presets:
        - "gd://"  # gradient descent algorithm with default parameters
        - "basic://" # basic tracking algorithm (alternating periods of exploration and dwell at vmpp) with default parameters
        - "gd://10:0.0001:10" # gd://alpha:min_step:NPLC --> alpha is the learning rate, min_step is the smallest possible voltage step, larger NPLC means slower, more accurate measurements
        - "basic://7:10" # basic://degrees:dwell_time --> larger degrees means wider exploration, larger dwell_time means longer dwell periods

# controls for how "smart mode" works
smart_mode:
    enabled: false
    # when using smart mode, start scan 1 and end scan 2 this many percent higher than Voc
    # bigger numbers here give better fitting for series resistance at an increased danger of pushing too much current through the device
    percent_beyond_voc: 25
    # when using smart mode, end scan 1 and start scan 2 this much into reverse bias
    # bigger numbers here give better fitting for shunt resistance at an increased danger of pulling too much current from the device
    # this is an absolute number whose sign is set depending on the sign of Voc
    voltage_beyond_isc: 0.1

# networking configuration parameters
network:
    MQTTHOST: "127.0.0.1"
    live_data_uris:
        - "http://127.0.0.1:8051/"  # for V vs T plot
        - "http://127.0.0.1:8052/"  # for J vs V plot
        - "http://127.0.0.1:8053/"  # for MPPT plots
        - "http://127.0.0.1:8054/"  # for J vs T plot
        - "http://127.0.0.1:8055/"  # for EQE plot
        - "https://duckduckgo.com/" # for custom webview tab

visa:
    visa_lib: '@py'

# stage and mux controller network address
controller:
    address: "10.42.0.239"

# source-measure unit(s)
smu:
    enabled: true
    address: "ASRL/dev/ttyS0::INSTR"
    #address: "GPIB::24::INSTR"
    baud: 57600  # only relevant for serial comms
    # HINT: "\r" = <CR>, "\r\n" = <CR+LF>, "\n" = <LF>, "\n\r" = <LF+CR>
    terminator: "\r"  # only relevant for serial comms
    # if front terminals is false, then use rear terminals
    front_terminals: false
    # if 2 wire is false, then use 4 wire
    two_wire: false

solarsim:
    enabled: false
    #address: "wavelabs://0.0.0.0:3334"
    address: "wavelabs-relay://127.0.0.1:3335"
    recipes:
      - "am1_5_1_sun"
      - "Christo Disco"
    spectral_calibration: null

# lock-in amplifier
lia:
    enabled: false
    address: "ASRL/dev/ttyUSB0::INSTR"
    terminator: "\r"
    baud: 9600
    output_interface: 0
    auto_gain_method: "instr"  # user or instr
    ratio: true  # true to use AUX1 input signal to account for lamp output drift

monochromator:
    enabled: false
    address: "ASRL/dev/ttyUSB2::INSTR"
    terminator: "\r"
    baud: 9600
    grating_change_wls: [1200]
    filter_change_wls: [370, 640, 715, 765]

# LED power supply unit
psu:
    enabled: false
    address: "TCPIP0::192.168.1.235::INSTR"
    terminator: "\r"  # only relevant for serial comms
    baud: 9600  # only relevant for serial comms
    ch1_voltage: 3.9
    ch2_voltage: 1.9
    ch3_voltage: 0
    ch1_ocp : 0.7
    ch2_ocp : 0.7
    ch3_ocp : 0.0

stage:
    enabled: true
    # stage connection URI
    # tells the system how to talk to the stage.
    # format = controller-type://list,of,expected,travel,lengths,in,mm/steps_per_mm/list of lists of keepout zones per axis/extra_info
    # typical travel lengths might be X = 1000mm (stage length) - 125 (gantry width) = 875 and Y = 500mm (stage length) - 125 (gantry width) = 375
    # typical steps per mm might be 256[uSteps/step] (microstepping driver property) * 200[steps/rev] (motor property) / 8[mm/rev] (leadscrew property) = 6400 [uSteps/mm]
    # the keepout zone list is a list (with of length matching the expected travel lengths), each item in the list is a list of length two specifying the regions along an axis that are not allowed
    # for example: [[],[62.5,Infinity]] means all values in X are okay, but any place beyond 62.5mm in Y is invalid
    # [[],[]] means no limits for either axis
    # the final field contains extra info for controlling the stage, for example "otter" tells the system to use a special homing procedure specific to one hardware setup
    uri: "us://375/6400"
    #uri: "us://125/6400"

    # approx mm/s (used for timing calculations only, does not actually set speed)
    speed: 29

    # a list of true/false, one for each axis. these will tell the system which direction "forward" is for that axis
    flip_axis_polarity: [true]
    #flip_axis_polarity: [false, false]
    
    # coordinates of the center of the substrate array for specific measurement types
    experiment_positions:
        solarsim: [174]
        #eqe: [800, 250]
    
        # these just show up in a list in the GUI to make it easier to move somewhere
    # experiment_positions are auto included in that list
    custom_positions:
        Load Position: [355]
        Grey's fav spot: [88.54241]
        Midway: [187.5]
        Offline Position: [20]

# a section for describing how the substrates are positioned and what might be on them
substrates:
    # list of number of substrates along each available axis: [x-direction, y-direction]
    number: [8]
    #number: [4, 5]
    
    # spacing in mm between substrate centers along each available axis
    spacing: [40]
    #spacing: [35, 29]

    # a list of true/false, one for each axis. these will tell the system
    # if the labels along that axis direction should be flipped
    # this might be needed to get the labels to match the physical array layout
    flip_labels: [false]
    #flip_labels: [false, true]
    
    # the section for device layout information
    # the first one listed here will be considered the default
    layouts:
        # Oxford 30x30 layout with one 1cm device
        one large:
            # enabled means the layout is something that can be selected in the GUI
            enabled: true
            # which of the the (changeable) PCB adapter boards this layout uses
            pcb_name: 30x30mm
            # outer dimensions of the substrate in mm
            size: [30, 30]
            # list of PCB adapter board pad the devices of this layout use
            pads:       [1,              2,              3,          4,         5,             6]
            # list of position vectors of each pixel describing where they are on the substrate
            # positions are given in mm, [x, y], relative to the substrate center
            locations:  [[-3.43, -8.16], [-8.05, 4.33],  [0, -4.33], [0, 4.33], [3.43, -8.16], [8.05, 4.33]]
            # list describing the shapes of the illuminated areas. s for square, c for circle
            # a number indicates the device shape is rectangular, with the number being the length in x
            shapes:     [s,              5.41,           21.5,       5.41,      s,             5.41]
            # list of illumination areas in cm^2 of each device
            areas:      [0.01,           0.25,           1,          0.25,      0.01,          0.25]
            # list of active areas in cm^2 of each device
            dark_areas: [0.01,           0.3087,         1.1392,     0.3087,    0.01,          0.3087]

        two large:
            enabled: true
            pcb_name: 30x30mm
            size: [30, 30]
            pads:       [1,              2,             3,          4,         5,             6]
            locations:  [[-8.16, -3.43], [8.16, -3.43], [-4.33, 0], [4.33, 0], [-8.16, 3.43], [8.16, 3.43]]
            shapes:     [s,              s,             4.66,       4.66,      s,             s]
            areas:      [0.01,           0.01,          1,          1,         0.01,          0.01]
            dark_areas: [0.01,           0.01,          1.1392,     1.1392,    0.01,          0.01]

        # Oxford 30x30 layout with no 1cm devices (6 medium ones)
        no large:
            enabled: true
            pcb_name: 30x30mm
            size: [30, 30]
            pads:       [1,               2,             3,          4,         5,             6]
            locations:  [[-4.33, -8.05],  [4.33, -8.05], [-4.33, 0], [4.33, 0], [-4.33, 8.05], [4.33, 8.05]]
            shapes:     [4.66,            4.66,          4.66,       4.66,      4.66,          4.66]
            areas:      [0.25,            0.25,          0.25,       0.25,      0.25,          0.25]
            dark_areas: [0.3087,          0.3087,        0.3087,     0.3087,    0.3087,        0.3087]

        # Oxford 30x30 photodiode boards
        BPW34s:
            enabled: true
            pcb_name: 30x30mm
            size: [30, 30]
            pads:       [1,              2,             3,          4,         5,             6]
            locations:  [[-8.05, -4.33], [-8.05, 4.33], [0, -4.33], [0, 4.33], [8.05, -4.33], [8.05, 4.33]]
            shapes:     [s,              s,             s,          s,         s,             s]
            areas:      [0.075,          0.075,         0.075,      0.075,     0.075,         0.075]
            dark_areas: [0.075,          0.075,         0.075,      0.075,     0.075,         0.075]

        # OLD Oxford 30x30 layout with one 1cm device
        OLD one large:
            enabled: true
            pcb_name: 30x30mm
            size: [30, 30]
            pads:       [2,           3,          4,         6]
            locations:  [[6.2, -7.1], [-6.35, 0], [6.2, 0],  [6.2, 7.1]]
            shapes:     [4.02,        5.28,       4.02,      4.02]
            areas:      [0.2,         1,          0.2,       0.2]
            dark_areas: [0.2730,      1.1565,     0.2730,    0.2730]

        # OLD Oxford 30x30 layout with two 1cm devices
        OLD two large:
            enabled: true
            pcb_name: 30x30mm
            size: [30, 30]
            pads:       [3,          4]
            locations:  [[-6.35, 0], [6.35, 0]]
            shapes:     [5.28,       5.28]
            areas:      [1,          1]
            dark_areas: [1.1565,     1.1565]

        # OLD Oxford 30x30 layout with no 1cm devices (6 medium ones)
        OLD no large:
            enabled: true
            pcb_name: 30x30mm
            size: [30, 30]
            pads:       [1,             2,           3,         4,        5,           6]
            locations:  [[-6.2, -7.1],  [6.2, -7.1], [-6.2, 0], [6.2, 0], [-6.2, 7.1], [6.2, 7.1]]
            shapes:     [4.02,          4.02,        4.02,      4.02,     4.02,        4.02]
            areas:      [0.2,           0.2,         0.2,       0.2,      0.2,         0.2]
            dark_areas: [0.2730,        0.2730,      0.2730,    0.2730,   0.2730,      0.2730]

        # legacy Oxford 28x28 layout
        28x28 legacy:
            enabled: true
            pcb_name: 28x28mm
            size: [28, 28]
            pads:       [1,               2,              3,               4,              5,                6,               7,                8]
            locations:  [[-6.536, 7.022], [4.971, 7.027], [-4.959, 2.347], [6.522, 2.349], [-6.522, -2.349], [4.959, -2.347], [-4.971, -7.027], [6.536, -7.022]]  # "upd"
            shapes:     [c,               c,              c,               c,              c,                c,               c,                c]
            areas:      [0.09294,         0.09294,        0.09294,         0.09294,        0.09294,          0.09294,         0.09294,          0.09294]  # "upd"
           #areas:      [0.13461,         0.13461,        0.13461,         0.13461,        0.13461,          0.13461,         0.13461,          0.13461]  # "new"
            dark_areas: [0.13747,         0.15211,        0.14833,         0.13282,        0.13282,          0.14833,         0.15211,          0.15747]  # "upd"

        # for when there's nothing loaded
        empty:
            enabled: true
            pcb_name: na
            size: []
            pads: []
            locations: []
            shapes: []
            areas: []
            dark_areas: []


    # this section describes the possible adapter PCBs that may be installed in each slot
    # these are the boards with the gold spring pins
    adapters:
        30x30mm:
            # pcb adapter board identification resistor value (in Ohms)
            pcb_resistor: 0

        28x28mm:
            pcb_resistor: 0

        1x1in:
            pcb_resistor: 0

        # for when an adapter board is not used (external measurement for example)
        na:
            pcb_resistor: inf

# miscellaneous reference data
reference:
    # spectral irradiance data
    spectra: null
    # device calibration data
    calibration:
        eqe:
          wls: [350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000, 1050, 1100]
          eqe: [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
